# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(606, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 0, 581, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 180, 281, 131))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 281, 111))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.A1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.A1.setObjectName("A1")
        self.horizontalLayout.addWidget(self.A1)
        self.A2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.A2.setObjectName("A2")
        self.horizontalLayout.addWidget(self.A2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.N1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.N1.setObjectName("N1")
        self.horizontalLayout_2.addWidget(self.N1)
        self.N2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.N2.setObjectName("N2")
        self.horizontalLayout_2.addWidget(self.N2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 61, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 30, 221, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.project = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.project.setObjectName("project")
        self.verticalLayout_2.addWidget(self.project)
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget_2)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 9, 18), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_2.addWidget(self.dateEdit)
        self.floor = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.floor.setObjectName("floor")
        self.verticalLayout_2.addWidget(self.floor)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 310, 231, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 227, 51))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.CC1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.CC1.setObjectName("CC1")
        self.verticalLayout_4.addWidget(self.CC1)
        self.CC2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.CC2.setObjectName("CC2")
        self.verticalLayout_4.addWidget(self.CC2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 380, 231, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(20, 20, 227, 81))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.DL1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.DL1.setObjectName("DL1")
        self.verticalLayout_6.addWidget(self.DL1)
        self.DL2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.DL2.setObjectName("DL2")
        self.verticalLayout_6.addWidget(self.DL2)
        self.DL3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.DL3.setObjectName("DL3")
        self.verticalLayout_6.addWidget(self.DL3)
        self.Pic1 = DropIn(self.tab)
        self.Pic1.setGeometry(QtCore.QRect(310, 30, 120, 90))
        self.Pic1.setAcceptDrops(True)
        self.Pic1.setAutoFillBackground(False)
        self.Pic1.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic1.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic1.setObjectName("Pic1")
        self.Pic2 = DropIn(self.tab)
        self.Pic2.setGeometry(QtCore.QRect(440, 30, 120, 90))
        self.Pic2.setAcceptDrops(True)
        self.Pic2.setAutoFillBackground(False)
        self.Pic2.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic2.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic2.setObjectName("Pic2")
        self.Pic3 = DropIn(self.tab)
        self.Pic3.setGeometry(QtCore.QRect(310, 130, 120, 90))
        self.Pic3.setAcceptDrops(True)
        self.Pic3.setAutoFillBackground(False)
        self.Pic3.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic3.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic3.setObjectName("Pic3")
        self.Pic4 = DropIn(self.tab)
        self.Pic4.setGeometry(QtCore.QRect(440, 130, 120, 90))
        self.Pic4.setAcceptDrops(True)
        self.Pic4.setAutoFillBackground(False)
        self.Pic4.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic4.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic4.setObjectName("Pic4")
        self.Pic7 = DropIn(self.tab)
        self.Pic7.setGeometry(QtCore.QRect(310, 330, 120, 90))
        self.Pic7.setAcceptDrops(True)
        self.Pic7.setAutoFillBackground(False)
        self.Pic7.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic7.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic7.setObjectName("Pic7")
        self.Pic5 = DropIn(self.tab)
        self.Pic5.setGeometry(QtCore.QRect(310, 230, 120, 90))
        self.Pic5.setAcceptDrops(True)
        self.Pic5.setAutoFillBackground(False)
        self.Pic5.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic5.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic5.setObjectName("Pic5")
        self.Pic6 = DropIn(self.tab)
        self.Pic6.setGeometry(QtCore.QRect(440, 230, 120, 90))
        self.Pic6.setAcceptDrops(True)
        self.Pic6.setAutoFillBackground(False)
        self.Pic6.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic6.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic6.setObjectName("Pic6")
        self.Pic8 = DropIn(self.tab)
        self.Pic8.setGeometry(QtCore.QRect(440, 330, 120, 90))
        self.Pic8.setAcceptDrops(True)
        self.Pic8.setAutoFillBackground(False)
        self.Pic8.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic8.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic8.setObjectName("Pic8")
        self.Pic10 = DropIn(self.tab)
        self.Pic10.setGeometry(QtCore.QRect(440, 430, 120, 90))
        self.Pic10.setAcceptDrops(True)
        self.Pic10.setAutoFillBackground(False)
        self.Pic10.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic10.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic10.setObjectName("Pic10")
        self.Pic9 = DropIn(self.tab)
        self.Pic9.setGeometry(QtCore.QRect(310, 430, 120, 90))
        self.Pic9.setAcceptDrops(True)
        self.Pic9.setAutoFillBackground(False)
        self.Pic9.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic9.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic9.setObjectName("Pic9")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(0, 570, 571, 32))
        self.pushButton.setObjectName("pushButton")
        self.clearpic = QtWidgets.QPushButton(self.tab)
        self.clearpic.setGeometry(QtCore.QRect(311, 530, 251, 32))
        self.clearpic.setObjectName("clearpic")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(9, 479, 281, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit.setGeometry(QtCore.QRect(3, 20, 281, 61))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton2.setGeometry(QtCore.QRect(0, 570, 571, 32))
        self.pushButton2.setObjectName("pushButton2")
        self.Pic6_2 = DropIn(self.tab_3)
        self.Pic6_2.setGeometry(QtCore.QRect(440, 230, 120, 90))
        self.Pic6_2.setAcceptDrops(True)
        self.Pic6_2.setAutoFillBackground(False)
        self.Pic6_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic6_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic6_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic6_2.setObjectName("Pic6_2")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 180, 281, 81))
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayoutWidget_19 = QtWidgets.QWidget(self.groupBox_13)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(0, 20, 281, 53))
        self.verticalLayoutWidget_19.setObjectName("verticalLayoutWidget_19")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_19)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_19)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_10.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_19)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_10.addWidget(self.label_26)
        self.verticalLayout_22.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.A1_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_19)
        self.A1_2.setObjectName("A1_2")
        self.horizontalLayout_9.addWidget(self.A1_2)
        self.N1_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_19)
        self.N1_2.setObjectName("N1_2")
        self.horizontalLayout_9.addWidget(self.N1_2)
        self.verticalLayout_22.addLayout(self.horizontalLayout_9)
        self.clearpic_2 = QtWidgets.QPushButton(self.tab_3)
        self.clearpic_2.setGeometry(QtCore.QRect(311, 530, 251, 32))
        self.clearpic_2.setObjectName("clearpic_2")
        self.Pic3_2 = DropIn(self.tab_3)
        self.Pic3_2.setGeometry(QtCore.QRect(310, 130, 120, 90))
        self.Pic3_2.setAcceptDrops(True)
        self.Pic3_2.setAutoFillBackground(False)
        self.Pic3_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic3_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic3_2.setObjectName("Pic3_2")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 270, 231, 101))
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayoutWidget_21 = QtWidgets.QWidget(self.groupBox_14)
        self.verticalLayoutWidget_21.setGeometry(QtCore.QRect(20, 20, 227, 81))
        self.verticalLayoutWidget_21.setObjectName("verticalLayoutWidget_21")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_21)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.CC1_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_21)
        self.CC1_2.setEnabled(False)
        self.CC1_2.setObjectName("CC1_2")
        self.verticalLayout_23.addWidget(self.CC1_2)
        self.CC2_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_21)
        self.CC2_2.setEnabled(False)
        self.CC2_2.setObjectName("CC2_2")
        self.verticalLayout_23.addWidget(self.CC2_2)
        self.CC3_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_21)
        self.CC3_2.setEnabled(False)
        self.CC3_2.setObjectName("CC3_2")
        self.verticalLayout_23.addWidget(self.CC3_2)
        self.verticalLayoutWidget_22 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_22.setGeometry(QtCore.QRect(70, 30, 221, 141))
        self.verticalLayoutWidget_22.setObjectName("verticalLayoutWidget_22")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_22)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.project2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_22)
        self.project2.setObjectName("project2")
        self.verticalLayout_24.addWidget(self.project2)
        self.dateEdit2 = QtWidgets.QDateEdit(self.verticalLayoutWidget_22)
        self.dateEdit2.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 9, 18), QtCore.QTime(0, 0, 0)))
        self.dateEdit2.setObjectName("dateEdit2")
        self.verticalLayout_24.addWidget(self.dateEdit2)
        self.floor2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_22)
        self.floor2.setObjectName("floor2")
        self.verticalLayout_24.addWidget(self.floor2)
        self.comboBox2 = QtWidgets.QComboBox(self.verticalLayoutWidget_22)
        self.comboBox2.setEditable(False)
        self.comboBox2.setObjectName("comboBox2")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.verticalLayout_24.addWidget(self.comboBox2)
        self.Pic5_2 = DropIn(self.tab_3)
        self.Pic5_2.setGeometry(QtCore.QRect(310, 230, 120, 90))
        self.Pic5_2.setAcceptDrops(True)
        self.Pic5_2.setAutoFillBackground(False)
        self.Pic5_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic5_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic5_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic5_2.setObjectName("Pic5_2")
        self.Pic2_2 = DropIn(self.tab_3)
        self.Pic2_2.setGeometry(QtCore.QRect(440, 30, 120, 90))
        self.Pic2_2.setAcceptDrops(True)
        self.Pic2_2.setAutoFillBackground(False)
        self.Pic2_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic2_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic2_2.setObjectName("Pic2_2")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 380, 231, 101))
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayoutWidget_23 = QtWidgets.QWidget(self.groupBox_15)
        self.verticalLayoutWidget_23.setGeometry(QtCore.QRect(20, 20, 227, 81))
        self.verticalLayoutWidget_23.setObjectName("verticalLayoutWidget_23")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_23)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.DL1_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_23)
        self.DL1_2.setObjectName("DL1_2")
        self.verticalLayout_25.addWidget(self.DL1_2)
        self.DL2_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_23)
        self.DL2_2.setObjectName("DL2_2")
        self.verticalLayout_25.addWidget(self.DL2_2)
        self.DL3_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_23)
        self.DL3_2.setObjectName("DL3_2")
        self.verticalLayout_25.addWidget(self.DL3_2)
        self.Pic9_2 = DropIn(self.tab_3)
        self.Pic9_2.setGeometry(QtCore.QRect(310, 430, 120, 90))
        self.Pic9_2.setAcceptDrops(True)
        self.Pic9_2.setAutoFillBackground(False)
        self.Pic9_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic9_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic9_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic9_2.setObjectName("Pic9_2")
        self.Pic4_2 = DropIn(self.tab_3)
        self.Pic4_2.setGeometry(QtCore.QRect(440, 130, 120, 90))
        self.Pic4_2.setAcceptDrops(True)
        self.Pic4_2.setAutoFillBackground(False)
        self.Pic4_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic4_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic4_2.setObjectName("Pic4_2")
        self.Pic7_2 = DropIn(self.tab_3)
        self.Pic7_2.setGeometry(QtCore.QRect(310, 330, 120, 90))
        self.Pic7_2.setAcceptDrops(True)
        self.Pic7_2.setAutoFillBackground(False)
        self.Pic7_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic7_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic7_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic7_2.setObjectName("Pic7_2")
        self.Pic1_2 = DropIn(self.tab_3)
        self.Pic1_2.setGeometry(QtCore.QRect(310, 30, 120, 90))
        self.Pic1_2.setAcceptDrops(True)
        self.Pic1_2.setAutoFillBackground(False)
        self.Pic1_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic1_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic1_2.setObjectName("Pic1_2")
        self.Pic8_2 = DropIn(self.tab_3)
        self.Pic8_2.setGeometry(QtCore.QRect(440, 330, 120, 90))
        self.Pic8_2.setAcceptDrops(True)
        self.Pic8_2.setAutoFillBackground(False)
        self.Pic8_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic8_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic8_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic8_2.setObjectName("Pic8_2")
        self.Pic10_2 = DropIn(self.tab_3)
        self.Pic10_2.setGeometry(QtCore.QRect(440, 430, 120, 90))
        self.Pic10_2.setAcceptDrops(True)
        self.Pic10_2.setAutoFillBackground(False)
        self.Pic10_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic10_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic10_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic10_2.setObjectName("Pic10_2")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_16.setGeometry(QtCore.QRect(9, 479, 281, 81))
        self.groupBox_16.setObjectName("groupBox_16")
        self.remark2 = QtWidgets.QTextEdit(self.groupBox_16)
        self.remark2.setGeometry(QtCore.QRect(3, 20, 281, 61))
        self.remark2.setObjectName("remark2")
        self.verticalLayoutWidget_24 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_24.setGeometry(QtCore.QRect(10, 30, 61, 131))
        self.verticalLayoutWidget_24.setObjectName("verticalLayoutWidget_24")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_24)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_24)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_26.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget_24)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_26.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget_24)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_26.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget_24)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_26.addWidget(self.label_30)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Pic8_3 = DropIn(self.tab_2)
        self.Pic8_3.setGeometry(QtCore.QRect(440, 330, 120, 90))
        self.Pic8_3.setAcceptDrops(True)
        self.Pic8_3.setAutoFillBackground(False)
        self.Pic8_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic8_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic8_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic8_3.setObjectName("Pic8_3")
        self.Pic7_3 = DropIn(self.tab_2)
        self.Pic7_3.setGeometry(QtCore.QRect(310, 330, 120, 90))
        self.Pic7_3.setAcceptDrops(True)
        self.Pic7_3.setAutoFillBackground(False)
        self.Pic7_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic7_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic7_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic7_3.setObjectName("Pic7_3")
        self.Pic5_3 = DropIn(self.tab_2)
        self.Pic5_3.setGeometry(QtCore.QRect(310, 230, 120, 90))
        self.Pic5_3.setAcceptDrops(True)
        self.Pic5_3.setAutoFillBackground(False)
        self.Pic5_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic5_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic5_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic5_3.setObjectName("Pic5_3")
        self.Pic1_3 = DropIn(self.tab_2)
        self.Pic1_3.setGeometry(QtCore.QRect(310, 30, 120, 90))
        self.Pic1_3.setAcceptDrops(True)
        self.Pic1_3.setAutoFillBackground(False)
        self.Pic1_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic1_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic1_3.setObjectName("Pic1_3")
        self.Pic10_3 = DropIn(self.tab_2)
        self.Pic10_3.setGeometry(QtCore.QRect(440, 430, 120, 90))
        self.Pic10_3.setAcceptDrops(True)
        self.Pic10_3.setAutoFillBackground(False)
        self.Pic10_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic10_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic10_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic10_3.setObjectName("Pic10_3")
        self.Pic3_3 = DropIn(self.tab_2)
        self.Pic3_3.setGeometry(QtCore.QRect(310, 130, 120, 90))
        self.Pic3_3.setAcceptDrops(True)
        self.Pic3_3.setAutoFillBackground(False)
        self.Pic3_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic3_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic3_3.setObjectName("Pic3_3")
        self.Pic2_3 = DropIn(self.tab_2)
        self.Pic2_3.setGeometry(QtCore.QRect(440, 30, 120, 90))
        self.Pic2_3.setAcceptDrops(True)
        self.Pic2_3.setAutoFillBackground(False)
        self.Pic2_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic2_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic2_3.setObjectName("Pic2_3")
        self.Pic6_3 = DropIn(self.tab_2)
        self.Pic6_3.setGeometry(QtCore.QRect(440, 230, 120, 90))
        self.Pic6_3.setAcceptDrops(True)
        self.Pic6_3.setAutoFillBackground(False)
        self.Pic6_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic6_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic6_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic6_3.setObjectName("Pic6_3")
        self.Pic4_3 = DropIn(self.tab_2)
        self.Pic4_3.setGeometry(QtCore.QRect(440, 130, 120, 90))
        self.Pic4_3.setAcceptDrops(True)
        self.Pic4_3.setAutoFillBackground(False)
        self.Pic4_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic4_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic4_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic4_3.setObjectName("Pic4_3")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_17.setGeometry(QtCore.QRect(10, 180, 281, 81))
        self.groupBox_17.setObjectName("groupBox_17")
        self.verticalLayoutWidget_20 = QtWidgets.QWidget(self.groupBox_17)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(0, 20, 281, 53))
        self.verticalLayoutWidget_20.setObjectName("verticalLayoutWidget_20")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_20)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget_20)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_11.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.verticalLayoutWidget_20)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_11.addWidget(self.label_32)
        self.verticalLayout_27.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.A1_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_20)
        self.A1_3.setObjectName("A1_3")
        self.horizontalLayout_12.addWidget(self.A1_3)
        self.N1_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_20)
        self.N1_3.setObjectName("N1_3")
        self.horizontalLayout_12.addWidget(self.N1_3)
        self.verticalLayout_27.addLayout(self.horizontalLayout_12)
        self.verticalLayoutWidget_25 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_25.setGeometry(QtCore.QRect(10, 30, 61, 131))
        self.verticalLayoutWidget_25.setObjectName("verticalLayoutWidget_25")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_25)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget_25)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_28.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.verticalLayoutWidget_25)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_28.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.verticalLayoutWidget_25)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_28.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.verticalLayoutWidget_25)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_28.addWidget(self.label_36)
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_18.setGeometry(QtCore.QRect(9, 479, 281, 81))
        self.groupBox_18.setObjectName("groupBox_18")
        self.remark3 = QtWidgets.QTextEdit(self.groupBox_18)
        self.remark3.setGeometry(QtCore.QRect(3, 20, 281, 61))
        self.remark3.setObjectName("remark3")
        self.verticalLayoutWidget_26 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_26.setGeometry(QtCore.QRect(70, 30, 221, 141))
        self.verticalLayoutWidget_26.setObjectName("verticalLayoutWidget_26")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_26)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.project3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_26)
        self.project3.setObjectName("project3")
        self.verticalLayout_29.addWidget(self.project3)
        self.dateEdit3 = QtWidgets.QDateEdit(self.verticalLayoutWidget_26)
        self.dateEdit3.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 9, 18), QtCore.QTime(0, 0, 0)))
        self.dateEdit3.setObjectName("dateEdit3")
        self.verticalLayout_29.addWidget(self.dateEdit3)
        self.floor3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_26)
        self.floor3.setObjectName("floor3")
        self.verticalLayout_29.addWidget(self.floor3)
        self.comboBox3 = QtWidgets.QComboBox(self.verticalLayoutWidget_26)
        self.comboBox3.setEditable(False)
        self.comboBox3.setObjectName("comboBox3")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.verticalLayout_29.addWidget(self.comboBox3)
        self.clearpic_3 = QtWidgets.QPushButton(self.tab_2)
        self.clearpic_3.setGeometry(QtCore.QRect(311, 530, 251, 32))
        self.clearpic_3.setObjectName("clearpic_3")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_19.setGeometry(QtCore.QRect(10, 270, 231, 101))
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayoutWidget_27 = QtWidgets.QWidget(self.groupBox_19)
        self.verticalLayoutWidget_27.setGeometry(QtCore.QRect(20, 20, 227, 81))
        self.verticalLayoutWidget_27.setObjectName("verticalLayoutWidget_27")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_27)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.CC1_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_27)
        self.CC1_3.setEnabled(False)
        self.CC1_3.setObjectName("CC1_3")
        self.verticalLayout_30.addWidget(self.CC1_3)
        self.CC2_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_27)
        self.CC2_3.setEnabled(False)
        self.CC2_3.setObjectName("CC2_3")
        self.verticalLayout_30.addWidget(self.CC2_3)
        self.CC3_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_27)
        self.CC3_3.setEnabled(False)
        self.CC3_3.setObjectName("CC3_3")
        self.verticalLayout_30.addWidget(self.CC3_3)
        self.Pic9_3 = DropIn(self.tab_2)
        self.Pic9_3.setGeometry(QtCore.QRect(310, 430, 120, 90))
        self.Pic9_3.setAcceptDrops(True)
        self.Pic9_3.setAutoFillBackground(False)
        self.Pic9_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Pic9_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Pic9_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic9_3.setObjectName("Pic9_3")
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_20.setGeometry(QtCore.QRect(10, 380, 231, 101))
        self.groupBox_20.setObjectName("groupBox_20")
        self.verticalLayoutWidget_28 = QtWidgets.QWidget(self.groupBox_20)
        self.verticalLayoutWidget_28.setGeometry(QtCore.QRect(20, 20, 227, 81))
        self.verticalLayoutWidget_28.setObjectName("verticalLayoutWidget_28")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_28)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.DL1_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_28)
        self.DL1_3.setObjectName("DL1_3")
        self.verticalLayout_31.addWidget(self.DL1_3)
        self.DL2_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_28)
        self.DL2_3.setObjectName("DL2_3")
        self.verticalLayout_31.addWidget(self.DL2_3)
        self.DL3_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_28)
        self.DL3_3.setObjectName("DL3_3")
        self.verticalLayout_31.addWidget(self.DL3_3)
        self.pushButton3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton3.setGeometry(QtCore.QRect(0, 570, 571, 32))
        self.pushButton3.setObjectName("pushButton3")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 606, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.comboBox.setCurrentIndex(0)
        self.comboBox2.setCurrentIndex(0)
        self.comboBox3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Grid"))
        self.label_4.setText(_translate("MainWindow", "Aphabet"))
        self.label_5.setText(_translate("MainWindow", "Number"))
        self.label.setText(_translate("MainWindow", "Project"))
        self.label_2.setText(_translate("MainWindow", "Date"))
        self.label_3.setText(_translate("MainWindow", "Floor"))
        self.label_6.setText(_translate("MainWindow", "Building"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Cedar"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Cedar"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Ebony"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Oak"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Pine"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Lobby"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Parking area"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Ebony wing"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Road area"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Crack Characteristic"))
        self.CC1.setText(_translate("MainWindow", "Buttom of slab"))
        self.CC2.setText(_translate("MainWindow", "Top of slab"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Danage Level"))
        self.DL1.setText(_translate("MainWindow", "Severe"))
        self.DL2.setText(_translate("MainWindow", "Moderate"))
        self.DL3.setText(_translate("MainWindow", "Least"))
        self.Pic1.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic2.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic3.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic4.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic7.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic5.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic6.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic8.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic10.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic9.setText(_translate("MainWindow", "Drop Picture here"))
        self.pushButton.setText(_translate("MainWindow", "Generate Report"))
        self.clearpic.setText(_translate("MainWindow", "Clear Picture"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Remark"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Floor"))
        self.pushButton2.setText(_translate("MainWindow", "Generate Report"))
        self.Pic6_2.setText(_translate("MainWindow", "Drop Picture here"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Grid"))
        self.label_25.setText(_translate("MainWindow", "Aphabet"))
        self.label_26.setText(_translate("MainWindow", "Number"))
        self.clearpic_2.setText(_translate("MainWindow", "Clear Picture"))
        self.Pic3_2.setText(_translate("MainWindow", "Drop Picture here"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Crack Characteristic"))
        self.CC1_2.setText(_translate("MainWindow", "Horizontal Crack"))
        self.CC2_2.setText(_translate("MainWindow", "Vertical Crack"))
        self.CC3_2.setText(_translate("MainWindow", "Inclination Crack"))
        self.comboBox2.setCurrentText(_translate("MainWindow", "Cedar"))
        self.comboBox2.setItemText(0, _translate("MainWindow", "Cedar"))
        self.comboBox2.setItemText(1, _translate("MainWindow", "Ebony"))
        self.comboBox2.setItemText(2, _translate("MainWindow", "Oak"))
        self.comboBox2.setItemText(3, _translate("MainWindow", "Pine"))
        self.comboBox2.setItemText(4, _translate("MainWindow", "Lobby"))
        self.comboBox2.setItemText(5, _translate("MainWindow", "Parking area"))
        self.comboBox2.setItemText(6, _translate("MainWindow", "Ebony wing"))
        self.comboBox2.setItemText(7, _translate("MainWindow", "Road area"))
        self.Pic5_2.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic2_2.setText(_translate("MainWindow", "Drop Picture here"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Danage Level"))
        self.DL1_2.setText(_translate("MainWindow", "Severe"))
        self.DL2_2.setText(_translate("MainWindow", "Moderate"))
        self.DL3_2.setText(_translate("MainWindow", "Least"))
        self.Pic9_2.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic4_2.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic7_2.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic1_2.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic8_2.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic10_2.setText(_translate("MainWindow", "Drop Picture here"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Remark"))
        self.label_27.setText(_translate("MainWindow", "Project"))
        self.label_28.setText(_translate("MainWindow", "Date"))
        self.label_29.setText(_translate("MainWindow", "Floor"))
        self.label_30.setText(_translate("MainWindow", "Building"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Column"))
        self.Pic8_3.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic7_3.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic5_3.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic1_3.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic10_3.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic3_3.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic2_3.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic6_3.setText(_translate("MainWindow", "Drop Picture here"))
        self.Pic4_3.setText(_translate("MainWindow", "Drop Picture here"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Grid"))
        self.label_31.setText(_translate("MainWindow", "Number"))
        self.label_32.setText(_translate("MainWindow", "Number"))
        self.label_33.setText(_translate("MainWindow", "Project"))
        self.label_34.setText(_translate("MainWindow", "Date"))
        self.label_35.setText(_translate("MainWindow", "Floor"))
        self.label_36.setText(_translate("MainWindow", "Building"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Remark"))
        self.comboBox3.setCurrentText(_translate("MainWindow", "Cedar"))
        self.comboBox3.setItemText(0, _translate("MainWindow", "Cedar"))
        self.comboBox3.setItemText(1, _translate("MainWindow", "Ebony"))
        self.comboBox3.setItemText(2, _translate("MainWindow", "Oak"))
        self.comboBox3.setItemText(3, _translate("MainWindow", "Pine"))
        self.comboBox3.setItemText(4, _translate("MainWindow", "Lobby"))
        self.comboBox3.setItemText(5, _translate("MainWindow", "Parking area"))
        self.comboBox3.setItemText(6, _translate("MainWindow", "Ebony wing"))
        self.comboBox3.setItemText(7, _translate("MainWindow", "Road area"))
        self.clearpic_3.setText(_translate("MainWindow", "Clear Picture"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Crack Characteristic"))
        self.CC1_3.setText(_translate("MainWindow", "Horizontal Crack"))
        self.CC2_3.setText(_translate("MainWindow", "Vertical Crack"))
        self.CC3_3.setText(_translate("MainWindow", "Inclination Crack"))
        self.Pic9_3.setText(_translate("MainWindow", "Drop Picture here"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Danage Level"))
        self.DL1_3.setText(_translate("MainWindow", "Severe"))
        self.DL2_3.setText(_translate("MainWindow", "Moderate"))
        self.DL3_3.setText(_translate("MainWindow", "Least"))
        self.pushButton3.setText(_translate("MainWindow", "Generate Report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Beam"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Wall"))
from dropin import DropIn


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
