"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Master.py']
DATA_FILES = ['Floor.pdf', 'Column.pdf']
OPTIONS = {'includes': ['pdfrw', 'reportlab'], 'packages': ['pdfrw', 'reportlab']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=['pdfrw', 'reportlab'],
)
